// ============================================================
// ALL user-visible strings live here. Edit once, changes everywhere.
// ============================================================

export const LABELS = {
  appName: 'MFG Portal',
  appSubtitle: 'Manufacturing Portal',
  connected: 'Connected to ERPNext v15',
  disconnected: 'Disconnected',
  loading: 'Loading…',
  error: 'Something went wrong',
  retry: 'Retry',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  submit: 'Submit',
  confirm: 'Confirm',
  search: 'Search…',
  viewInPortal: 'View in Portal',

  workOrder: 'Work Order',
  bom: 'BOM',
  jobCard: 'Job Card',
  stockEntry: 'Stock Entry',
  productionPlan: 'Production Plan',
  workstation: 'Workstation',
  operation: 'Operation',
  stock: 'Stock / Items',
  item: 'Item',

  nav: {
    workOrders: 'Work Orders',
    bom: 'BOM',
    jobCards: 'Job Cards',
    stockEntries: 'Stock Entries',
    productionPlans: 'Production Plans',
    stock: 'Stock / Items',
    mainMenu: 'MANUFACTURING',
    // Sales & Accounts
    salesOrders: 'Sales Orders',
    deliveryNotes: 'Delivery Notes',
    salesInvoices: 'Sales Invoices',
    payments: 'Payments',
    // Reports
    reports: 'Reports',
    profitLoss: 'Profit & Loss',
    grossProfit: 'Gross Profit',
    balanceSheet: 'Balance Sheet',
    trialBalance: 'Trial Balance',
    generalLedger: 'General Ledger',
    stockLedgerReport: 'Stock Ledger',
    stockBalance: 'Stock Balance',
    stockProjected: 'Stock Projected Qty',
  },

  // Theme
  theme: {
    toggle: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
  },

  // Document page tabs
  docTabs: {
    details: 'Details',
    items: 'Items / Child Tables',
    stockLedger: 'Stock Ledger',
    accountingLedger: 'Accounting Ledger',
    linkedDocs: 'Linked Documents',
    activity: 'Activity',
    timeLogs: 'Time Logs',
  },

  // Ledger
  ledger: {
    stockLedger: 'Stock Ledger',
    accountingLedger: 'Accounting Ledger',
    noStockEntries: 'No stock ledger entries for this document.',
    noGLEntries: 'No accounting ledger entries for this document.',
    balanced: 'Balanced',
    totalValueMoved: 'Total Value Moved',
    impactSummary: 'Impact Summary',
    totalDebit: 'Total Debit',
    totalCredit: 'Total Credit',
  },

  // Flow stepper
  stepper: {
    workOrder: 'Work Order',
    materialTransfer: 'Material Transfer',
    jobCard: 'Job Card',
    manufacture: 'Manufacture',
    deliveryNote: 'Delivery Note',
    salesInvoice: 'Sales Invoice',
    paymentEntry: 'Payment Entry',
    profitLoss: 'Profit & Loss',
  },

  // Reports
  reportLabels: {
    profitLoss: 'Profit and Loss Statement',
    grossProfit: 'Gross Profit',
    balanceSheet: 'Balance Sheet',
    trialBalance: 'Trial Balance',
    generalLedger: 'General Ledger',
    stockLedger: 'Stock Ledger',
    stockBalance: 'Stock Balance',
    stockProjected: 'Stock Projected Qty',
    runReport: 'Run Report',
    refresh: 'Refresh',
    exportCsv: 'Export CSV',
    print: 'Print',
    expandAll: 'Expand All',
    collapseAll: 'Collapse All',
    noData: 'No data for the selected filters.',
    lastRun: 'Last run',
    drillDown: 'Drill down',
  },

  // Report filter labels
  reportFilters: {
    company: 'Company',
    filterBasedOn: 'Filter Based On',
    fiscalYear: 'Fiscal Year',
    dateRange: 'Date Range',
    fromFiscalYear: 'From Fiscal Year',
    toFiscalYear: 'To Fiscal Year',
    periodStart: 'Period Start Date',
    periodEnd: 'Period End Date',
    periodicity: 'Periodicity',
    accumulatedValues: 'Accumulated Values',
    costCenter: 'Cost Center',
    project: 'Project',
    currency: 'Presentation Currency',
    fromDate: 'From Date',
    toDate: 'To Date',
    account: 'Account',
    partyType: 'Party Type',
    party: 'Party',
    voucherNo: 'Voucher No',
    groupBy: 'Group By',
    item: 'Item',
    warehouse: 'Warehouse',
    batch: 'Batch',
    itemGroup: 'Item Group',
    customer: 'Customer',
    salesPerson: 'Sales Person',
  },

  metrics: {
    activeWorkOrders: 'Active Work Orders',
    openJobCards: 'Open Job Cards',
    stockAlerts: 'Stock Alerts',
    completedBatches: 'Completed Batches',
  },

  status: {
    notStarted: 'Not Started',
    inProcess: 'In Process',
    completed: 'Completed',
    stopped: 'Stopped',
    closed: 'Closed',
    cancelled: 'Cancelled',
    draft: 'Draft',
    open: 'Open',
    workInProgress: 'Work In Progress',
    materialTransferred: 'Material Transferred',
    onHold: 'On Hold',
    submitted: 'Submitted',
  },

  actions: {
    newWorkOrder: '+ New Work Order',
    startTransfer: 'Start (Material Transfer)',
    finishManufacture: 'Finish (Manufacture)',
    stopWorkOrder: 'Stop Work Order',
    resumeWorkOrder: 'Resume Work Order',
    viewDetails: 'View Details',
    logout: 'Logout',
  },

  columns: {
    workOrder: {
      id: 'ID',
      item: 'Item',
      plannedQty: 'Planned Qty',
      producedQty: 'Produced Qty',
      wipWarehouse: 'WIP Warehouse',
      status: 'Status',
      created: 'Created',
    },
    bom: {
      id: 'BOM ID',
      item: 'Item',
      quantity: 'Quantity',
      totalCost: 'Total Cost',
      isDefault: 'Default',
      withOperations: 'Operations',
    },
    jobCard: {
      id: 'ID',
      workOrder: 'Work Order',
      item: 'Item',
      workstation: 'Workstation',
      operation: 'Operation',
      requiredTime: 'Required (h)',
      actualTime: 'Actual (min)',
      status: 'Status',
    },
    stockEntry: {
      id: 'ID',
      type: 'Type',
      workOrder: 'Work Order',
      date: 'Date',
      outgoing: 'Outgoing (₹)',
      incoming: 'Incoming (₹)',
      status: 'Status',
    },
    productionPlan: {
      id: 'ID',
      date: 'Date',
      status: 'Status',
      plannedQty: 'Planned Qty',
      producedQty: 'Produced Qty',
    },
    stock: {
      item: 'Item',
      warehouse: 'Warehouse',
      actualQty: 'Actual Qty',
      reorderLevel: 'Reorder Level',
      level: 'Level',
      valuationRate: 'Val. Rate (₹)',
      stockValue: 'Stock Value (₹)',
    },
    bomRaw: {
      item: 'Item',
      qty: 'Qty',
      uom: 'UOM',
      rate: 'Rate (₹)',
      amount: 'Amount (₹)',
    },
    bomOps: {
      operation: 'Operation',
      workstation: 'Workstation',
      time: 'Time (min)',
      hourRate: 'Hour Rate (₹)',
    },
    bomScrap: {
      item: 'Item',
      qty: 'Qty',
      rate: 'Rate (₹)',
      amount: 'Amount (₹)',
    },
    salesOrder: {
      id: 'Order ID',
      customer: 'Customer',
      date: 'Date',
      deliveryDate: 'Delivery Date',
      grandTotal: 'Grand Total (₹)',
      status: 'Status',
      deliveryStatus: 'Delivery Status',
      billingStatus: 'Billing Status',
    },
    deliveryNote: {
      id: 'Delivery Note ID',
      customer: 'Customer',
      date: 'Posting Date',
      grandTotal: 'Total (₹)',
      status: 'Status',
    },
    salesInvoice: {
      id: 'Invoice ID',
      customer: 'Customer',
      date: 'Posting Date',
      grandTotal: 'Grand Total (₹)',
      outstanding: 'Outstanding (₹)',
      status: 'Status',
    },
    paymentEntry: {
      id: 'Payment ID',
      party: 'Party',
      type: 'Payment Type',
      date: 'Posting Date',
      paid: 'Paid Amount (₹)',
      received: 'Received Amount (₹)',
      status: 'Status',
    },
  },

  empty: {
    workOrders: 'No Work Orders found.',
    bom: 'No active BOMs found.',
    jobCards: 'No Job Cards found.',
    stockEntries: 'No Stock Entries found.',
    productionPlans: 'No Production Plans found.',
    stock: 'No stock data found.',
    linkedJobCards: 'No linked Job Cards.',
    linkedStockEntries: 'No linked Stock Entries.',
    bomRaw: 'No raw materials.',
    bomOps: 'No operations.',
    bomScrap: 'No scrap items.',
    salesOrders: 'No Sales Orders found.',
    deliveryNotes: 'No Delivery Notes found.',
    salesInvoices: 'No Sales Invoices found.',
    paymentEntries: 'No Payment Entries found.',
  },

  modal: {
    newWorkOrder: 'New Work Order',
    selectItem: 'Production Item',
    qty: 'Quantity',
    bom: 'BOM (Bill of Materials)',
    wipWarehouse: 'WIP Warehouse',
    fgWarehouse: 'Finished Goods Warehouse',
    scrapWarehouse: 'Scrap Warehouse',
    sourceWarehouse: 'Source Warehouse',
    step1: 'Select Item & Quantity',
    step2: 'Configure Warehouses',
    creating: 'Creating Work Order…',
  },

  drawer: {
    workOrderDetails: 'Work Order Details',
    linkedJobCards: 'Linked Job Cards',
    linkedStockEntries: 'Linked Stock Entries',
    bomDetails: 'BOM Details',
    rawMaterials: 'Raw Materials',
    operations: 'Operations',
    scrapItems: 'Scrap Items',
    costSummary: 'Cost Summary',
  },

  userMenu: {
    viewProfile: 'View Profile',
    apps: 'Apps',
    switchToDesk: 'Switch to Desk',
    signOut: 'Sign Out',
    connectedTo: 'Connected to',
  },

  profile: {
    title: 'User Profile',
    subtitle: 'Account details and assigned roles',
    fullName: 'Full Name',
    email: 'Email',
    roles: 'Roles',
    language: 'Language',
    userType: 'User Type',
    status: 'Status',
    active: 'Active',
    disabled: 'Disabled',
    noRoles: 'No roles assigned.',
    readOnlyNotice: 'This is a read-only view of your ERPNext user profile.',
  },
} as const;

export type Labels = typeof LABELS;
